<?php
/* @var $this EmployeeController */
/* @var $dataProvider CActiveDataProvider */

$this->breadcrumbs=array(
    'Employees',
);

$this->menu=array(
    array('label'=>'Create Employee', 'url'=>array('create')),
    array('label'=>'Manage Employee', 'url'=>array('admin')),
);
?>

<!--<h1>Employees</h1>-->

<!-- redirect to the specific view for the signed in user-->
<?php
    $this->redirect(array('view', 'id'=>Yii::app()->user->getId())); 
?>

<!-- first ClistView generated by the CRUD generator -->
<?php 
/*
$this->widget('zii.widgets.CListView', array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_view',
)); 
*/
?>
